// @ts-check
﻿(function () {
  const BASE_CONFIG = {
    unitContactRequestTimeoutMs: 15000,
    attachmentsRequestTimeoutMs: 15000,
    unitContactStatusLookupMethod: 'POST',
    unitContactStatusQueryParam: 'email',
    unitContactSharedHeaders: {},
    correctiveActionsMode: 'local-emulator',
    correctiveActionsEndpoint: '',
    correctiveActionsHealthEndpoint: '',
    correctiveActionsSharedHeaders: {},
    checklistMode: 'local-emulator',
    checklistEndpoint: '',
    checklistHealthEndpoint: '',
    checklistSharedHeaders: {},
    trainingMode: 'local-emulator',
    trainingFormsEndpoint: '',
    trainingRostersEndpoint: '',
    trainingHealthEndpoint: '',
    trainingSharedHeaders: {},
    authMode: 'local-emulator',
    authEndpoint: '',
    authHealthEndpoint: '',
    authSharedHeaders: {},
    systemUsersMode: 'local-emulator',
    systemUsersEndpoint: '',
    systemUsersHealthEndpoint: '',
    systemUsersSharedHeaders: {},
    reviewScopesMode: 'local-emulator',
    reviewScopesEndpoint: '',
    reviewScopesHealthEndpoint: '',
    reviewScopesSharedHeaders: {},
    auditTrailMode: 'local-emulator',
    auditTrailEndpoint: '',
    auditTrailHealthEndpoint: '',
    auditTrailSharedHeaders: {},
    attachmentsMode: 'local-emulator',
    attachmentsEndpoint: '',
    attachmentsHealthEndpoint: '',
    attachmentsSharedHeaders: {},
    unitContactActivationEndpoint: '',
    sharePointSiteName: 'ISMS-Forms',
    sharePointSiteUrl: '',
    sharePointLists: {
      applications: 'UnitContactApplications',
      unitAdmins: 'UnitAdmins',
      audit: 'OpsAudit',
      correctiveActions: 'CorrectiveActions',
      checklists: 'Checklists',
      trainingForms: 'TrainingForms',
      trainingRosters: 'TrainingRosters',
      systemUsers: 'SystemUsers',
      reviewScopes: 'UnitReviewScopes'
    },
    entraTenantId: '',
    entraClientId: '',
    activationPathBase: '#activate-unit-contact'
  };

  const DEPLOYMENT_PROFILES = {
    localDemo: {
      label: 'Local demo / browser-only mode',
      unitContactMode: 'local-emulator',
      unitContactSubmitEndpoint: '',
      unitContactStatusEndpoint: '',
      correctiveActionsMode: 'local-emulator',
      correctiveActionsEndpoint: '',
      checklistMode: 'local-emulator',
      checklistEndpoint: '',
      trainingMode: 'local-emulator',
      trainingFormsEndpoint: '',
      trainingRostersEndpoint: ''
    },
    a3CampusFlow: {
      label: 'A3-ready campus frontend + SharePoint / Power Automate',
      unitContactMode: 'sharepoint-flow',
      unitContactSubmitEndpoint: 'https://YOUR-POWER-AUTOMATE-ENDPOINT-HOST/workflows/.../triggers/manual/paths/invoke',
      unitContactStatusEndpoint: 'https://YOUR-POWER-AUTOMATE-ENDPOINT-HOST/workflows/.../triggers/manual/paths/invoke',
      unitContactStatusLookupMethod: 'POST',
      sharePointSiteUrl: 'https://YOUR-TENANT.sharepoint.com/sites/ISMS-Forms'
    },
    a3SiteOwnerFlow: {
      label: 'A3 fallback: site owner + SharePoint / Power Automate',
      unitContactMode: 'sharepoint-flow',
      unitContactSubmitEndpoint: 'https://YOUR-POWER-AUTOMATE-ENDPOINT-HOST/workflows/.../triggers/manual/paths/invoke',
      unitContactStatusEndpoint: 'https://YOUR-POWER-AUTOMATE-ENDPOINT-HOST/workflows/.../triggers/manual/paths/invoke',
      unitContactStatusLookupMethod: 'POST',
      sharePointSiteUrl: 'https://YOUR-TENANT.sharepoint.com/sites/ISMS-Forms',
      sharePointSiteName: 'ISMS-Forms',
      sharePointProvisioningModel: 'delegated-site-owner'
    },
    a3CampusBackend: {
      label: 'A3 fallback: campus backend + SharePoint lists',
      strictRemoteData: true,
      unitContactMode: 'm365-api',
      unitContactSubmitEndpoint: '/api/unit-contact/apply',
      unitContactStatusEndpoint: '/api/unit-contact/status',
      correctiveActionsMode: 'm365-api',
      correctiveActionsEndpoint: '/api/corrective-actions',
      correctiveActionsHealthEndpoint: '/api/corrective-actions/health',
      checklistMode: 'm365-api',
      checklistEndpoint: '/api/checklists',
      checklistHealthEndpoint: '/api/checklists/health',
      trainingMode: 'm365-api',
      trainingFormsEndpoint: '/api/training/forms',
      trainingRostersEndpoint: '/api/training/rosters',
      trainingHealthEndpoint: '/api/training/health',
      authMode: 'm365-api',
      authEndpoint: '/api/auth',
      authHealthEndpoint: '/api/auth/health',
      systemUsersMode: 'm365-api',
      systemUsersEndpoint: '/api/system-users',
      systemUsersHealthEndpoint: '/api/system-users/health',
      reviewScopesMode: 'm365-api',
      reviewScopesEndpoint: '/api/review-scopes',
      reviewScopesHealthEndpoint: '/api/review-scopes/health',
      auditTrailMode: 'm365-api',
      auditTrailEndpoint: '/api/audit-trail',
      auditTrailHealthEndpoint: '/api/audit-trail/health',
      attachmentsMode: 'm365-api',
      attachmentsEndpoint: '/api/attachments',
      attachmentsHealthEndpoint: '/api/attachments/health',
      unitContactActivationEndpoint: '#activate-unit-contact',
      unitContactStatusLookupMethod: 'POST',
      sharePointSiteUrl: 'https://YOUR-TENANT.sharepoint.com/sites/ISMSFormsWorkspace',
      sharePointSiteName: 'ISMSFormsWorkspace',
      sharePointProvisioningModel: 'delegated-site-owner'
    },
    azureFunctionCampus: {
      label: 'Campus frontend + Azure Function backend',
      strictRemoteData: true,
      unitContactMode: 'm365-api',
      unitContactSubmitEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/unit-contact/apply',
      unitContactStatusEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/unit-contact/status',
      correctiveActionsMode: 'm365-api',
      correctiveActionsEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/corrective-actions',
      correctiveActionsHealthEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/corrective-actions/health',
      checklistMode: 'm365-api',
      checklistEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/checklists',
      checklistHealthEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/checklists/health',
      trainingMode: 'm365-api',
      trainingFormsEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/training/forms',
      trainingRostersEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/training/rosters',
      trainingHealthEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/training/health',
      authMode: 'm365-api',
      authEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/auth',
      authHealthEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/auth/health',
      systemUsersMode: 'm365-api',
      systemUsersEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/system-users',
      systemUsersHealthEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/system-users/health',
      reviewScopesMode: 'm365-api',
      reviewScopesEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/review-scopes',
      reviewScopesHealthEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/review-scopes/health',
      auditTrailMode: 'm365-api',
      auditTrailEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/audit-trail',
      auditTrailHealthEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/audit-trail/health',
      attachmentsMode: 'm365-api',
      attachmentsEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/attachments',
      attachmentsHealthEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/attachments/health',
      unitContactActivationEndpoint: 'https://YOUR-FUNCTION-APP.azurewebsites.net/api/unit-contact/activate',
      sharePointSiteUrl: 'https://YOUR-TENANT.sharepoint.com/sites/ISMS-Forms'
    },
    googleCloudRun: {
      label: 'HTTPS frontend + Google Cloud Run backend',
      strictRemoteData: true,
      unitContactMode: 'm365-api',
      unitContactSubmitEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/unit-contact/apply',
      unitContactStatusEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/unit-contact/status',
      correctiveActionsMode: 'm365-api',
      correctiveActionsEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/corrective-actions',
      correctiveActionsHealthEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/corrective-actions/health',
      checklistMode: 'm365-api',
      checklistEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/checklists',
      checklistHealthEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/checklists/health',
      trainingMode: 'm365-api',
      trainingFormsEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/training/forms',
      trainingRostersEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/training/rosters',
      trainingHealthEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/training/health',
      authMode: 'm365-api',
      authEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/auth',
      authHealthEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/auth/health',
      systemUsersMode: 'm365-api',
      systemUsersEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/system-users',
      systemUsersHealthEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/system-users/health',
      reviewScopesMode: 'm365-api',
      reviewScopesEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/review-scopes',
      reviewScopesHealthEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/review-scopes/health',
      auditTrailMode: 'm365-api',
      auditTrailEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/audit-trail',
      auditTrailHealthEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/audit-trail/health',
      attachmentsMode: 'm365-api',
      attachmentsEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/attachments',
      attachmentsHealthEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/attachments/health',
      unitContactActivationEndpoint: 'https://YOUR-CLOUD-RUN-SERVICE.run.app/api/unit-contact/activate',
      sharePointSiteUrl: 'https://YOUR-TENANT.sharepoint.com/sites/ISMSFormsWorkspace',
      sharePointSiteName: 'ISMSFormsWorkspace',
      sharePointProvisioningModel: 'app-only-or-managed-identity'
    },
    cloudflarePagesTunnel: {
      label: 'Cloudflare Pages frontend + Cloudflare Tunnel backend',
      strictRemoteData: true,
      unitContactMode: 'm365-api',
      unitContactSubmitEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/unit-contact/apply',
      unitContactStatusEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/unit-contact/status',
      correctiveActionsMode: 'm365-api',
      correctiveActionsEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/corrective-actions',
      correctiveActionsHealthEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/corrective-actions/health',
      checklistMode: 'm365-api',
      checklistEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/checklists',
      checklistHealthEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/checklists/health',
      trainingMode: 'm365-api',
      trainingFormsEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/training/forms',
      trainingRostersEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/training/rosters',
      trainingHealthEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/training/health',
      authMode: 'm365-api',
      authEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/auth',
      authHealthEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/auth/health',
      systemUsersMode: 'm365-api',
      systemUsersEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/system-users',
      systemUsersHealthEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/system-users/health',
      reviewScopesMode: 'm365-api',
      reviewScopesEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/review-scopes',
      reviewScopesHealthEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/review-scopes/health',
      auditTrailMode: 'm365-api',
      auditTrailEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/audit-trail',
      auditTrailHealthEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/audit-trail/health',
      attachmentsMode: 'm365-api',
      attachmentsEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/attachments',
      attachmentsHealthEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/attachments/health',
      unitContactActivationEndpoint: 'https://YOUR-TUNNEL-HOSTNAME/api/unit-contact/activate',
      sharePointSiteUrl: 'https://YOUR-TENANT.sharepoint.com/sites/ISMSFormsWorkspace',
      sharePointSiteName: 'ISMSFormsWorkspace',
      sharePointProvisioningModel: 'delegated-cli-or-app-only'
    }
  };

  // Change only this value during deployment.
  // Recommended:
  // - local development: localDemo
  // - A3 production without Power Automate environment: a3CampusBackend
  // - A3 production without tenant admin: a3SiteOwnerFlow
  // - A3 production with tenant admin: a3CampusFlow
  // - future upgrade: azureFunctionCampus
  const ACTIVE_PROFILE = 'localDemo';

  DEPLOYMENT_PROFILES.sharePointFlowCampus = DEPLOYMENT_PROFILES.a3CampusFlow;

  const selectedProfile = DEPLOYMENT_PROFILES[ACTIVE_PROFILE] || DEPLOYMENT_PROFILES.localDemo;
  const runtimeOverride = window.__M365_UNIT_CONTACT_CONFIG_OVERRIDE__;

  window.__M365_UNIT_CONTACT_CONFIG__ = {
    ...BASE_CONFIG,
    ...selectedProfile,
    ...(runtimeOverride && typeof runtimeOverride === 'object' ? runtimeOverride : {}),
    activeProfile: (runtimeOverride && runtimeOverride.activeProfile) || ACTIVE_PROFILE,
    availableProfiles: Object.keys(DEPLOYMENT_PROFILES),
    deploymentChecklistDoc: 'docs/m365-unit-contact-go-live-runbook.md'
  };
})();

